default: &default
  adapter: sqlite3
  encoding: utf8
  pool: <%= ENV["DB_POOL"] || 5  %>
  timeout: 5000
  
development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3


production:
  <<: *default
  database: serializer-jets-2_production
  url: <%= ENV['DATABASE_URL'] %>
